/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/respuestaetiqueta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuestaetiqueta.id"];
          id_etiqueta?: parameters["rowFilter.respuestaetiqueta.id_etiqueta"];
          id_respuesta?: parameters["rowFilter.respuestaetiqueta.id_respuesta"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["respuestaetiqueta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** respuestaetiqueta */
          respuestaetiqueta?: definitions["respuestaetiqueta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuestaetiqueta.id"];
          id_etiqueta?: parameters["rowFilter.respuestaetiqueta.id_etiqueta"];
          id_respuesta?: parameters["rowFilter.respuestaetiqueta.id_respuesta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuestaetiqueta.id"];
          id_etiqueta?: parameters["rowFilter.respuestaetiqueta.id_etiqueta"];
          id_respuesta?: parameters["rowFilter.respuestaetiqueta.id_respuesta"];
        };
        body: {
          /** respuestaetiqueta */
          respuestaetiqueta?: definitions["respuestaetiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/regaloetiqueta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regaloetiqueta.id"];
          id_regalo?: parameters["rowFilter.regaloetiqueta.id_regalo"];
          id_etiqueta?: parameters["rowFilter.regaloetiqueta.id_etiqueta"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["regaloetiqueta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** regaloetiqueta */
          regaloetiqueta?: definitions["regaloetiqueta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regaloetiqueta.id"];
          id_regalo?: parameters["rowFilter.regaloetiqueta.id_regalo"];
          id_etiqueta?: parameters["rowFilter.regaloetiqueta.id_etiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regaloetiqueta.id"];
          id_regalo?: parameters["rowFilter.regaloetiqueta.id_regalo"];
          id_etiqueta?: parameters["rowFilter.regaloetiqueta.id_etiqueta"];
        };
        body: {
          /** regaloetiqueta */
          regaloetiqueta?: definitions["regaloetiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/regalo": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalo.id"];
          name?: parameters["rowFilter.regalo.name"];
          image?: parameters["rowFilter.regalo.image"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["regalo"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** regalo */
          regalo?: definitions["regalo"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalo.id"];
          name?: parameters["rowFilter.regalo.name"];
          image?: parameters["rowFilter.regalo.image"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalo.id"];
          name?: parameters["rowFilter.regalo.name"];
          image?: parameters["rowFilter.regalo.image"];
        };
        body: {
          /** regalo */
          regalo?: definitions["regalo"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/usuario": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usuario.id"];
          name?: parameters["rowFilter.usuario.name"];
          apellido?: parameters["rowFilter.usuario.apellido"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["usuario"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** usuario */
          usuario?: definitions["usuario"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usuario.id"];
          name?: parameters["rowFilter.usuario.name"];
          apellido?: parameters["rowFilter.usuario.apellido"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.usuario.id"];
          name?: parameters["rowFilter.usuario.name"];
          apellido?: parameters["rowFilter.usuario.apellido"];
        };
        body: {
          /** usuario */
          usuario?: definitions["usuario"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/respuesta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuesta.id"];
          name?: parameters["rowFilter.respuesta.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["respuesta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** respuesta */
          respuesta?: definitions["respuesta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuesta.id"];
          name?: parameters["rowFilter.respuesta.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.respuesta.id"];
          name?: parameters["rowFilter.respuesta.name"];
        };
        body: {
          /** respuesta */
          respuesta?: definitions["respuesta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/regalobeneficiario": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalobeneficiario.id"];
          id_regalo?: parameters["rowFilter.regalobeneficiario.id_regalo"];
          id_beneficiario?: parameters["rowFilter.regalobeneficiario.id_beneficiario"];
          id_usuario?: parameters["rowFilter.regalobeneficiario.id_usuario"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["regalobeneficiario"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** regalobeneficiario */
          regalobeneficiario?: definitions["regalobeneficiario"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalobeneficiario.id"];
          id_regalo?: parameters["rowFilter.regalobeneficiario.id_regalo"];
          id_beneficiario?: parameters["rowFilter.regalobeneficiario.id_beneficiario"];
          id_usuario?: parameters["rowFilter.regalobeneficiario.id_usuario"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.regalobeneficiario.id"];
          id_regalo?: parameters["rowFilter.regalobeneficiario.id_regalo"];
          id_beneficiario?: parameters["rowFilter.regalobeneficiario.id_beneficiario"];
          id_usuario?: parameters["rowFilter.regalobeneficiario.id_usuario"];
        };
        body: {
          /** regalobeneficiario */
          regalobeneficiario?: definitions["regalobeneficiario"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/beneficiario": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.beneficiario.id"];
          name?: parameters["rowFilter.beneficiario.name"];
          apellido?: parameters["rowFilter.beneficiario.apellido"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["beneficiario"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** beneficiario */
          beneficiario?: definitions["beneficiario"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.beneficiario.id"];
          name?: parameters["rowFilter.beneficiario.name"];
          apellido?: parameters["rowFilter.beneficiario.apellido"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.beneficiario.id"];
          name?: parameters["rowFilter.beneficiario.name"];
          apellido?: parameters["rowFilter.beneficiario.apellido"];
        };
        body: {
          /** beneficiario */
          beneficiario?: definitions["beneficiario"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/etiqueta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.etiqueta.id"];
          name?: parameters["rowFilter.etiqueta.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["etiqueta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** etiqueta */
          etiqueta?: definitions["etiqueta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.etiqueta.id"];
          name?: parameters["rowFilter.etiqueta.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.etiqueta.id"];
          name?: parameters["rowFilter.etiqueta.name"];
        };
        body: {
          /** etiqueta */
          etiqueta?: definitions["etiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/pregunta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pregunta.id"];
          nombre?: parameters["rowFilter.pregunta.nombre"];
          image?: parameters["rowFilter.pregunta.image"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["pregunta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** pregunta */
          pregunta?: definitions["pregunta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pregunta.id"];
          nombre?: parameters["rowFilter.pregunta.nombre"];
          image?: parameters["rowFilter.pregunta.image"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pregunta.id"];
          nombre?: parameters["rowFilter.pregunta.nombre"];
          image?: parameters["rowFilter.pregunta.image"];
        };
        body: {
          /** pregunta */
          pregunta?: definitions["pregunta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/favorito": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorito.id"];
          id_usuario?: parameters["rowFilter.favorito.id_usuario"];
          id_regalo?: parameters["rowFilter.favorito.id_regalo"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["favorito"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** favorito */
          favorito?: definitions["favorito"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorito.id"];
          id_usuario?: parameters["rowFilter.favorito.id_usuario"];
          id_regalo?: parameters["rowFilter.favorito.id_regalo"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorito.id"];
          id_usuario?: parameters["rowFilter.favorito.id_usuario"];
          id_regalo?: parameters["rowFilter.favorito.id_regalo"];
        };
        body: {
          /** favorito */
          favorito?: definitions["favorito"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/preguntaetiqueta": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.preguntaetiqueta.id"];
          id_pregunta?: parameters["rowFilter.preguntaetiqueta.id_pregunta"];
          id_etiqueta?: parameters["rowFilter.preguntaetiqueta.id_etiqueta"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["preguntaetiqueta"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** preguntaetiqueta */
          preguntaetiqueta?: definitions["preguntaetiqueta"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.preguntaetiqueta.id"];
          id_pregunta?: parameters["rowFilter.preguntaetiqueta.id_pregunta"];
          id_etiqueta?: parameters["rowFilter.preguntaetiqueta.id_etiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.preguntaetiqueta.id"];
          id_pregunta?: parameters["rowFilter.preguntaetiqueta.id_pregunta"];
          id_etiqueta?: parameters["rowFilter.preguntaetiqueta.id_etiqueta"];
        };
        body: {
          /** preguntaetiqueta */
          preguntaetiqueta?: definitions["preguntaetiqueta"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  respuestaetiqueta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `etiqueta.id`.<fk table='etiqueta' column='id'/>
     */
    id_etiqueta?: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `respuesta.id`.<fk table='respuesta' column='id'/>
     */
    id_respuesta?: number;
  };
  regaloetiqueta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `regalo.id`.<fk table='regalo' column='id'/>
     */
    id_regalo?: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `etiqueta.id`.<fk table='etiqueta' column='id'/>
     */
    id_etiqueta?: number;
  };
  regalo: {
    price: any;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    image: string;
  };
  usuario: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name?: string;
    /** Format: character varying */
    apellido?: string;
  };
  respuesta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name?: string;
  };
  regalobeneficiario: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `regalo.id`.<fk table='regalo' column='id'/>
     */
    id_regalo: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `beneficiario.id`.<fk table='beneficiario' column='id'/>
     */
    id_beneficiario?: number;
    /** Format: uuid */
    id_usuario: string;
  };
  beneficiario: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name?: string;
    /** Format: character varying */
    apellido?: string;
  };
  etiqueta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name?: string;
  };
  pregunta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    nombre?: string;
    /** Format: character varying */
    image?: string;
  };
  favorito: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: bigint */
    id_usuario: number;
    /** Format: bigint */
    id_regalo: number;
  };
  preguntaetiqueta: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `pregunta.id`.<fk table='pregunta' column='id'/>
     */
    id_pregunta?: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `etiqueta.id`.<fk table='etiqueta' column='id'/>
     */
    id_etiqueta?: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description respuestaetiqueta */
  "body.respuestaetiqueta": definitions["respuestaetiqueta"];
  /** Format: bigint */
  "rowFilter.respuestaetiqueta.id": string;
  /** Format: bigint */
  "rowFilter.respuestaetiqueta.id_etiqueta": string;
  /** Format: bigint */
  "rowFilter.respuestaetiqueta.id_respuesta": string;
  /** @description regaloetiqueta */
  "body.regaloetiqueta": definitions["regaloetiqueta"];
  /** Format: bigint */
  "rowFilter.regaloetiqueta.id": string;
  /** Format: bigint */
  "rowFilter.regaloetiqueta.id_regalo": string;
  /** Format: bigint */
  "rowFilter.regaloetiqueta.id_etiqueta": string;
  /** @description regalo */
  "body.regalo": definitions["regalo"];
  /** Format: bigint */
  "rowFilter.regalo.id": string;
  /** Format: character varying */
  "rowFilter.regalo.name": string;
  /** Format: character varying */
  "rowFilter.regalo.image": string;
  /** @description usuario */
  "body.usuario": definitions["usuario"];
  /** Format: bigint */
  "rowFilter.usuario.id": string;
  /** Format: character varying */
  "rowFilter.usuario.name": string;
  /** Format: character varying */
  "rowFilter.usuario.apellido": string;
  /** @description respuesta */
  "body.respuesta": definitions["respuesta"];
  /** Format: bigint */
  "rowFilter.respuesta.id": string;
  /** Format: character varying */
  "rowFilter.respuesta.name": string;
  /** @description regalobeneficiario */
  "body.regalobeneficiario": definitions["regalobeneficiario"];
  /** Format: bigint */
  "rowFilter.regalobeneficiario.id": string;
  /** Format: bigint */
  "rowFilter.regalobeneficiario.id_regalo": string;
  /** Format: bigint */
  "rowFilter.regalobeneficiario.id_beneficiario": string;
  /** Format: uuid */
  "rowFilter.regalobeneficiario.id_usuario": string;
  /** @description beneficiario */
  "body.beneficiario": definitions["beneficiario"];
  /** Format: bigint */
  "rowFilter.beneficiario.id": string;
  /** Format: character varying */
  "rowFilter.beneficiario.name": string;
  /** Format: character varying */
  "rowFilter.beneficiario.apellido": string;
  /** @description etiqueta */
  "body.etiqueta": definitions["etiqueta"];
  /** Format: bigint */
  "rowFilter.etiqueta.id": string;
  /** Format: character varying */
  "rowFilter.etiqueta.name": string;
  /** @description pregunta */
  "body.pregunta": definitions["pregunta"];
  /** Format: bigint */
  "rowFilter.pregunta.id": string;
  /** Format: character varying */
  "rowFilter.pregunta.nombre": string;
  /** Format: character varying */
  "rowFilter.pregunta.image": string;
  /** @description favorito */
  "body.favorito": definitions["favorito"];
  /** Format: bigint */
  "rowFilter.favorito.id": string;
  /** Format: bigint */
  "rowFilter.favorito.id_usuario": string;
  /** Format: bigint */
  "rowFilter.favorito.id_regalo": string;
  /** @description preguntaetiqueta */
  "body.preguntaetiqueta": definitions["preguntaetiqueta"];
  /** Format: bigint */
  "rowFilter.preguntaetiqueta.id": string;
  /** Format: bigint */
  "rowFilter.preguntaetiqueta.id_pregunta": string;
  /** Format: bigint */
  "rowFilter.preguntaetiqueta.id_etiqueta": string;
}

export interface operations {}

export interface external {}
